import { describe, it, expect } from 'vitest';
import { generateIndex, titleCase, findNestedSections } from '../src/index-gen.js';
import { resolve } from 'path';

const FIXTURES = resolve(import.meta.dirname, 'index-gen-fixtures');
const FIXTURES_WITH_EXISTING_TITLE = resolve(import.meta.dirname, 'index-gen-fixtures-existing');
const FIXTURES_NESTED = resolve(import.meta.dirname, 'index-gen-fixtures-nested');

describe('generateIndex', () => {
  it('groups articles by category, counts them, and sorts slugs within a group', () => {
    const content = generateIndex(FIXTURES, 'Widget Api');

    expect(content).toContain('title: "Widget Api Index"');
    expect(content).toContain('# Widget Api Index');
    expect(content).toContain('## apis (1)');
    expect(content).toContain('## patterns (1)');
    expect(content).toContain('- [[widget-api]] — Widget CRUD API');
    expect(content).toContain('- [[auth-flow]] — Auth pattern for the widget API');
    expect(content).toContain('<!-- Generated by `kb index`. Do not edit by hand. -->');
  });

  it('groups articles with no category under "Other"', () => {
    const content = generateIndex(FIXTURES, 'Widget Api');
    expect(content).toContain('## Other (1)');
    expect(content).toContain('- [[uncategorized]]');
  });

  it('excludes _index.md and _summary.md from the catalog itself', () => {
    const content = generateIndex(FIXTURES, 'Widget Api');
    expect(content).not.toMatch(/\[\[_index\]\]/);
    expect(content).not.toMatch(/\[\[_summary\]\]/);
  });

  it('preserves an existing _index.md title instead of deriving a new one', () => {
    const content = generateIndex(FIXTURES_WITH_EXISTING_TITLE, 'Widget Api');
    expect(content).toContain('title: "Custom Existing Title"');
    expect(content).not.toContain('Widget Api Index');
  });

  it('derives a Title-Cased name from the wikiDir basename when no display name is given', () => {
    const content = generateIndex(FIXTURES);
    expect(content).toContain('title: "Index Gen Fixtures Index"');
  });
});

describe('titleCase', () => {
  it('splits on hyphens/underscores/spaces and capitalizes each word', () => {
    expect(titleCase('example-project')).toBe('Example Project');
    expect(titleCase('widget_api')).toBe('Widget Api');
  });
});

describe('generateIndex with nested sections', () => {
  it('lists a Sections link for a nested sub-wiki instead of duplicating its articles', () => {
    const content = generateIndex(FIXTURES_NESTED, 'Parent');

    // Sections group links to the nested section's own index, using its title.
    expect(content).toContain('## Sections (1)');
    expect(content).toContain('- [[child-section/_index]] — Child Section Index');

    // The nested section's article must NOT be duplicated into the parent.
    expect(content).not.toMatch(/\[\[child-article\]\]/);

    // Articles directly in the parent wiki are still listed normally.
    expect(content).toContain('- [[parent-article]] — An article directly in the parent wiki');
  });
});

describe('findNestedSections', () => {
  it('finds immediate nested sub-wikis and reads their title from frontmatter', () => {
    const sections = findNestedSections(FIXTURES_NESTED);
    expect(sections).toEqual([{ relDir: 'child-section', title: 'Child Section Index' }]);
  });

  it('returns nothing for a wikiDir with no nested _index.md files', () => {
    expect(findNestedSections(FIXTURES)).toEqual([]);
  });
});
